#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-WithHeader
version:      0.05
version_from: lib/IO/WithHeader.pm
installdirs:  site
requires:
    File::Copy:                    0
    IO::File:                      0
    Symbol:                        0
    Errno:                         0
    File::Slurp:                   0
    Text::Header:                  0
    Fcntl:                         0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
