#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-WithHeader
version:      0.04
version_from: lib/IO/WithHeader.pm
installdirs:  site
requires:
    IO::File:                      0
    YAML:                          0
    File::Slurp:                   0
    File::Copy:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
